/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern GoInt inits(char* src_ip, char* dst_ip, GoInt types);
extern GoInt parallel_tcp_data(GoUint32 s_port, GoUint32* d_ports, GoInt32 count, GoUint32 seq_num, GoUint32 ack_num, GoUint32* lengths);
extern GoInt parallel_rst(GoUint32 s_port, GoUint32 d_port, unsigned int* seq_nums, GoInt32 count, GoUint32 ack_num);
extern GoInt parallel_psh_ack(GoUint32 s_port, GoUint32 d_port, GoUint32 seq_num, unsigned int* ack_nums, GoInt32 ack_count);
extern GoInt parallel_ack_data(GoUint32 s_port, GoUint32 d_port, GoUint32 seq_num, GoUint32 ack_num, char* data, GoInt32 count);
extern GoInt parallel_udp_data(GoUint32 s_port, GoUint32* d_ports, GoInt32 count, GoInt32 min_length, GoInt32 max_length);
extern GoInt parallel_dns_response(GoUint32 s_port, GoUint32 d_port, GoUint32* trid, GoInt32 count);

#ifdef __cplusplus
}
#endif
